require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const supabase = require('../src/config/supabase');

async function seed() {
  console.log('Fetching existing categories...');
  const { data: categories, error: catError } = await supabase.from('categories').select('*');
  if (catError) {
    console.error('Error fetching categories:', catError);
    process.exit(1);
  }

  const catMap = {};
  categories.forEach((c) => {
    catMap[c.name] = c.id;
  });

  const items = [
    // --- ELECTRONICS (9 items) ---
    {
      name: 'Noise-Cancelling Wireless Headphones',
      description: 'Active noise cancellation with 35hr battery life and plush memory-foam ear cushions. Perfect for deep focus and travel.',
      price: 3999.00,
      image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 45,
      mood: 'work',
    },
    {
      name: 'Portable Waterproof Bluetooth Speaker',
      description: 'IPX7 waterproof wireless speaker delivering 360-degree bass. Built for outdoor parties and pool days.',
      price: 1799.00,
      original_price: 2499.00,
      image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 35,
      mood: 'party',
    },
    {
      name: 'Sunset Projection Lamp RGB',
      description: 'Golden hour aesthetic right in your room. 16 color modes with remote control for relaxation and photography.',
      price: 899.00,
      original_price: 1299.00,
      image_url: 'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 50,
      mood: 'relaxed',
    },
    {
      name: 'Dual-Wireless Ergonomic Mouse',
      description: 'Natural hand-shake posture design reduces wrist strain during long coding and office sessions.',
      price: 1199.00,
      original_price: 1699.00,
      image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 40,
      mood: 'work',
    },
    {
      name: 'Studio Ring Light with Tripod Stand',
      description: '10-inch dimmable LED ring light with warm/cool modes and universal smartphone mount for creators.',
      price: 1299.00,
      original_price: 1999.00,
      image_url: 'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 25,
      mood: 'happy',
    },
    {
      name: 'Fast-Charging Power Bank 20000mAh',
      description: 'Dual Type-C PD 22.5W high-speed charging bank capable of charging modern laptops and phones on the move.',
      price: 1599.00,
      original_price: 2199.00,
      image_url: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 60,
      mood: 'work',
    },
    {
      name: 'Smart AMOLED Fitness Tracker',
      description: 'Continuous heart-rate, SpO2, sleep tracking, and 120 sports modes with 14-day battery life.',
      price: 2199.00,
      original_price: 2999.00,
      image_url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 30,
      mood: 'happy',
    },
    {
      name: 'Wireless Karaoke Microphone with Speaker',
      description: 'Handheld Bluetooth mic with built-in stereo speaker and voice modifier effects. Instant party starter.',
      price: 999.00,
      original_price: 1499.00,
      image_url: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 20,
      mood: 'party',
    },
    {
      name: '4K Ultra HD Action Camera',
      description: 'Waterproof action cam with electronic image stabilization and wide-angle 170° lens for adventures.',
      price: 4999.00,
      original_price: 6999.00,
      image_url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Electronics'],
      stock: 15,
      mood: 'party',
    },

    // --- HOME & LIFESTYLE (9 items) ---
    {
      name: 'Ultrasonic Essential Oil Diffuser',
      description: '500ml aroma humidifier with ambient warm LED light and automatic shutoff for soothing evenings.',
      price: 1399.00,
      original_price: 1899.00,
      image_url: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 40,
      mood: 'relaxed',
    },
    {
      name: 'Chunky Knit Weighted Blanket',
      description: 'Hand-knitted breathable cotton weighted blanket designed to relieve anxiety and promote restful sleep.',
      price: 3499.00,
      original_price: 4999.00,
      image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 18,
      mood: 'relaxed',
    },
    {
      name: 'Natural Himalayan Pink Salt Lamp',
      description: 'Hand-carved authentic salt crystal lamp on wooden base emitting a warm, ion-rich soothing amber glow.',
      price: 849.00,
      original_price: 1199.00,
      image_url: 'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 50,
      mood: 'relaxed',
    },
    {
      name: 'Automatic Electric Wine Opener Kit',
      description: 'Cordless rechargeable corkscrew set with foil cutter, aerator pourer, and vacuum preserver stopper.',
      price: 1299.00,
      original_price: 1799.00,
      image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 30,
      mood: 'party',
    },
    {
      name: 'Ceramic Pour-Over Coffee Brewer',
      description: 'Artisan handcrafted ceramic dripper with wooden stand for rich, flavorful morning filter coffee.',
      price: 699.00,
      original_price: 999.00,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 35,
      mood: 'happy',
    },
    {
      name: 'Neon "Good Vibes Only" LED Sign',
      description: 'USB-powered vibrant neon acrylic wall art that sets an instant energetic party mood.',
      price: 1499.00,
      original_price: 2299.00,
      image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 22,
      mood: 'party',
    },
    {
      name: 'Memory Foam Ergonomic Neck Pillow',
      description: 'Orthopedic contoured support pillow for cervical spine alignment and deep restorative sleep.',
      price: 1699.00,
      original_price: 2399.00,
      image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 28,
      mood: 'relaxed',
    },
    {
      name: 'Ceramic Succulent Planters Set of 3',
      description: 'Minimalist white ceramic planters with bamboo drainage trays for desktop and window greenery.',
      price: 549.00,
      original_price: 799.00,
      image_url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 45,
      mood: 'happy',
    },
    {
      name: 'Smart Dual RGB Light Bars',
      description: 'Sound-sync ambient desk lights with app control and 16M colors for movies, gaming, and parties.',
      price: 2499.00,
      original_price: 3499.00,
      image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Home & Lifestyle'],
      stock: 25,
      mood: 'party',
    },

    // --- BOOKS (8 items) ---
    {
      name: 'Atomic Habits by James Clear',
      description: 'The definitive guide to breaking bad routines and building remarkable tiny habits for extraordinary results.',
      price: 499.00,
      original_price: 799.00,
      image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 80,
      mood: 'work',
    },
    {
      name: 'Ikigai: The Japanese Secret to Long Life',
      description: 'Discover the art of finding your purpose, living peacefully, and bringing joy to everyday rituals.',
      price: 349.00,
      original_price: 550.00,
      image_url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 65,
      mood: 'relaxed',
    },
    {
      name: 'Deep Work by Cal Newport',
      description: 'Rules for focused success in a distracted world. Master difficult tasks and produce at elite levels.',
      price: 420.00,
      original_price: 650.00,
      image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 40,
      mood: 'work',
    },
    {
      name: 'The Psychology of Money by Morgan Housel',
      description: 'Timeless lessons on wealth, greed, and happiness. How behavior matters far more than mathematical genius.',
      price: 399.00,
      original_price: 499.00,
      image_url: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 55,
      mood: 'work',
    },
    {
      name: 'The Comfort Book by Matt Haig',
      description: 'A pocket-sized hug of hope, short reflections, and reminders that there is always light at the end of hard days.',
      price: 450.00,
      original_price: 699.00,
      image_url: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 35,
      mood: 'happy',
    },
    {
      name: 'Show Your Work! by Austin Kleon',
      description: '10 ways to share your creativity and get discovered. Inspiring, practical guide for creators and builders.',
      price: 380.00,
      original_price: 599.00,
      image_url: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 45,
      mood: 'happy',
    },
    {
      name: 'The Little Book of Hygge',
      description: 'Danish secrets to cozy contentment, comfort food, warm lighting, and savoring simple pleasures.',
      price: 499.00,
      original_price: 750.00,
      image_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 30,
      mood: 'relaxed',
    },
    {
      name: 'Thinking, Fast and Slow by Daniel Kahneman',
      description: 'Nobel laureate exploration of the two systems that drive human thinking, judgment, and choices.',
      price: 599.00,
      original_price: 899.00,
      image_url: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Books'],
      stock: 25,
      mood: 'work',
    },

    // --- FOOD & BEVERAGES (8 items) ---
    {
      name: 'Ceremonial Japanese Matcha 50g',
      description: '100% stone-ground ceremonial green tea powder from Uji, Kyoto. Rich in antioxidants and clean, jitter-free energy.',
      price: 899.00,
      original_price: 1199.00,
      image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 50,
      mood: 'happy',
    },
    {
      name: 'Organic Chamomile Lavender Herbal Tea',
      description: 'Whole-flower caffeine-free herbal infusion designed for bedtime relaxation and calm mind.',
      price: 399.00,
      original_price: 549.00,
      image_url: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 60,
      mood: 'relaxed',
    },
    {
      name: 'Artisanal Dark Roast Whole Bean Coffee 250g',
      description: 'Single-origin Arabica beans roasted with notes of dark cocoa and toasted hazelnut for deep work mornings.',
      price: 549.00,
      original_price: 750.00,
      image_url: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 45,
      mood: 'work',
    },
    {
      name: 'Gourmet Himalayan Popcorn Trio Pack',
      description: 'Handcrafted non-GMO popcorn seasoned with Himalayan pink salt, caramel, and cheddar cheese.',
      price: 349.00,
      original_price: 499.00,
      image_url: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 70,
      mood: 'party',
    },
    {
      name: 'Cold Brew Coffee Concentrate 500ml',
      description: 'Smooth, 16-hour slow-steeped micro-filtered coffee concentrate. Just add cold water or milk over ice.',
      price: 449.00,
      original_price: 599.00,
      image_url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 35,
      mood: 'work',
    },
    {
      name: 'Raw Forest Wildflower Honey 500g',
      description: 'Unprocessed, unfiltered natural honey harvested from remote Himalayan forest reserves.',
      price: 499.00,
      original_price: 699.00,
      image_url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 40,
      mood: 'happy',
    },
    {
      name: 'Sparkling Artisan Kombucha 4-Pack',
      description: 'Naturally fermented sparkling probiotic iced tea with real ginger, passionfruit, and berries.',
      price: 649.00,
      original_price: 899.00,
      image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 30,
      mood: 'party',
    },
    {
      name: 'Dark Chocolate Sea Salt Roasted Almonds 200g',
      description: 'California almonds coated in 70% Belgian dark chocolate dusted with flaky Maldon sea salt.',
      price: 399.00,
      original_price: 549.00,
      image_url: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Food & Beverages'],
      stock: 55,
      mood: 'happy',
    },

    // --- FITNESS (8 items) ---
    {
      name: 'Deep Tissue Percussion Massage Gun',
      description: 'High-torque brushless motor with 6 massage heads and 30 speed levels for post-workout muscle recovery.',
      price: 2799.00,
      original_price: 3999.00,
      image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 25,
      mood: 'relaxed',
    },
    {
      name: 'Eco-Friendly Natural Cork Yoga Mat',
      description: 'Anti-microbial, sweat-activated non-slip cork surface with 5mm natural rubber base and carry strap.',
      price: 1699.00,
      original_price: 2499.00,
      image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 35,
      mood: 'relaxed',
    },
    {
      name: 'Adjustable Dumbbells Set (2kg - 10kg)',
      description: 'Space-saving home gym dumbbells with textured ergonomic grips and quick-change weight plates.',
      price: 3499.00,
      original_price: 4999.00,
      image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 20,
      mood: 'work',
    },
    {
      name: 'Insulated Stainless Steel Shaker 750ml',
      description: 'Double-walled vacuum insulated protein shaker keeps shakes ice cold for 24 hours with leakproof seal.',
      price: 799.00,
      original_price: 1199.00,
      image_url: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 45,
      mood: 'happy',
    },
    {
      name: 'High-Density Foam Roller for Recovery',
      description: 'Targeted myofascial release roller relieves back tightness, leg soreness, and boosts circulation.',
      price: 899.00,
      original_price: 1299.00,
      image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 40,
      mood: 'relaxed',
    },
    {
      name: 'Speed Jump Rope with Ball Bearings',
      description: 'Tangle-free steel cable jump rope for high-cadence cardio, boxing conditioning, and agility training.',
      price: 499.00,
      original_price: 799.00,
      image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 60,
      mood: 'happy',
    },
    {
      name: 'Weightlifting Wrist Wraps & Grips Pair',
      description: 'Heavy-duty thumb loop wrist braces providing maximum joint stability for heavy deadlifts and presses.',
      price: 599.00,
      original_price: 899.00,
      image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 30,
      mood: 'work',
    },
    {
      name: 'Acupressure Mat & Pillow Set',
      description: 'Thousands of stimulation points promote endorphin release, relieve muscular tension, and melt stress.',
      price: 1399.00,
      original_price: 1999.00,
      image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Fitness'],
      stock: 25,
      mood: 'relaxed',
    },

    // --- STATIONERY (8 items) ---
    {
      name: 'Hardcover Dotted Bullet Journal (160 GSM)',
      description: 'Bleed-resistant ultra-thick bamboo paper with numbered pages, inner pocket, and lay-flat binding.',
      price: 599.00,
      original_price: 899.00,
      image_url: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 75,
      mood: 'work',
    },
    {
      name: 'Solid Brass Minimalist Fountain Pen',
      description: 'Balanced heavyweight brass body with fine German iridium nib for butter-smooth handwriting.',
      price: 1299.00,
      original_price: 1899.00,
      image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 30,
      mood: 'work',
    },
    {
      name: 'Pastel Aesthetic Dual-Tip Highlighters 6-Pack',
      description: 'Soft pastel non-fluorescent colors gentle on the eyes with both chisel and fine bullet tips.',
      price: 349.00,
      original_price: 499.00,
      image_url: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 80,
      mood: 'happy',
    },
    {
      name: 'Ergonomic Felt Large Desk Pad (90x40cm)',
      description: 'Water-resistant natural wool felt desk blotter provides cushion for wrists and protects desktop.',
      price: 899.00,
      original_price: 1399.00,
      image_url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 40,
      mood: 'work',
    },
    {
      name: 'Sticky Notes & Page Flags Aesthetic Set',
      description: 'Color-palette coordinated translucent sticky tabs and memo pads for studying and organizing.',
      price: 299.00,
      original_price: 449.00,
      image_url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 90,
      mood: 'work',
    },
    {
      name: 'Undated Daily Productivity Planner',
      description: '90-day daily breakdown with priority matrices, habit tracking, and evening reflection prompts.',
      price: 499.00,
      original_price: 699.00,
      image_url: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 50,
      mood: 'happy',
    },
    {
      name: 'Japanese Calligraphy Brush Pens Set of 12',
      description: 'Flexible nylon brush tips with water-based blendable ink for lettering, sketching, and watercolor art.',
      price: 699.00,
      original_price: 999.00,
      image_url: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 35,
      mood: 'relaxed',
    },
    {
      name: 'Natural Walnut Wood Phone & Pen Stand',
      description: 'Solid handcrafted American walnut organizer keeps your charging phone and favorite pen in easy reach.',
      price: 749.00,
      original_price: 1099.00,
      image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      category_id: catMap['Stationery'],
      stock: 25,
      mood: 'work',
    },
  ];

  console.log(`Inserting ${items.length} new items into products table...`);
  const sanitizedItems = items.map(({ original_price, ...rest }) => rest);
  const { data, error } = await supabase.from('products').insert(sanitizedItems).select('id, name');

  if (error) {
    console.error('Error inserting items:', error);
    process.exit(1);
  }

  console.log(`Successfully added ${data.length} new products!`);
  data.forEach((p, idx) => console.log(`${idx + 1}. ${p.name}`));
}

seed();
